#!/bin/bash
source .install-helper

i i3-wm
i polybar
i arandr # GUI tool for monitor config using xrandr
i picom # compositor
i feh

# sudo apt install -y x11-xserver-utils
# sudo apt install -y clipit
# sudo apt install -y pm-utils

# see ~/.jensenr30/jenbox2/i3-init
